### ISSUE TITLE
id should be inside the json string

### ISSUE THREAD

**Issue by leafgecko** [sps-2020-summer/GroupBuySPS2020#9]
https://github.com/sps-2020-summer/GroupBuySPS2020/blob/apidoc/my-app/models/Offer.java#L33

**Comment by leafgecko** [comment]
can i check with you if the id should be removed?

**Comment by pohlinwei** [comment]
Nope. It should be there since we want to generate a new instance. 😅 By the way, could we do this over chat? It is quite inconvenient to hold a conversation over Github.
